CREATE DATABASE IF NOT EXISTS CochesDB;
USE CochesDB;
CREATE TABLE IF NOT EXISTS Coches(
Matricula CHAR(10) NOT NULL PRIMARY KEY,
Marca VARCHAR(20)NOT NULL COMMENT "Campo para la marca" ,
Modelo VARCHAR(25)NOT NULL COMMENT "Campo para el modelo",
Color VARCHAR(24)NOT NULL COMMENT "Campo para el color",
Precio DECIMAL(10,2)NOT NULL COMMENT "Campo para el precio"
);

SHOW TABLES;

CREATE DATABASE IF NOT EXISTS SociosDB;
USE SociosDB;

CREATE TABLE IF NOT EXISTS Socios(
Cod_socio INT UNSIGNED(5) ZEROFILL NOT NULL PRIMARY KEY,
DNI VARCHAR(10) NOT NULL UNIQUE,
Nombre VARCHAR(50) NOT NULL,
Email VARCHAR(30)NOT NULL DEFAULT 'Sin correo electrónico',
Fecha_Alta DATE NOT NULL,
);