-- Crear base de datos si no existe (en MySQL)
CREATE DATABASE IF NOT EXISTS Prueba1
    CHARACTER SET LATIN1
    COLLATE LATIN1_SWEDISH_CI;

-- Crear esquema si no existe (en MySQL no hay una forma directa de hacerlo en una sola sentencia)
CREATE SCHEMA IF NOT EXISTS Prueba2
    CHARACTER SET LATIN1
    COLLATE LATIN1_SWEDISH_CI;

-- Crear base de datos con COLLATE diferente
CREATE DATABASE IF NOT EXISTS Prueba3
    COLLATE BIG5_BIN;

SHOW DATABASES;

ALTER DATABASE Prueba2
CHARACTER SET UTF8
COLLATE UTF8_GENERAL_CI;

DROP DATABASE IF EXISTS Prueba1;
DROP DATABASE IF EXISTS Prueba2;

SHOW DATABASES;