CREATE DATABASE IF NOT EXISTS Productos;
USE Productos;

CREATE TABLE IF NOT EXISTS Fabricantes(

Cod_Fabricante INT UNSIGNED AUTO_INCREMENT,
Nombre VARCHAR(80)NOT NULL,
PRIMARY KEY (Cod_Fabricante)
);

CREATE TABLE IF NOT EXISTS Productos(
Cod_producto INT UNSIGNED AUTO_INCREMENT,
Nombre VARCHAR(55)NOT NULL,
Precio FLOAT NOT NULL,
Cantidad_Stock INT UNSIGNED NOT NULL,
IdFabricante INT UNSIGNED NOT NULL,
PRIMARY KEY (Cod_producto),
FOREIGN KEY(IdFabricante) REFERENCES Fabricantes(Cod_Fabricante)
   ON UPDATE CASCADE
   ON DELETE CASCADE
);


/*Ejercicio 2*/

CREATE DATABASE IF NOT EXISTS LiteraturaDB;
USE LiteraturaDB;
CREATE TABLE IF NOT EXISTS Autores(
Idautor CHAR(5)NOT NULL,
Nombre VARCHAR(40) NOT NULL DEFAULT '',
Apellido1 VARCHAR (30) NOT NULL DEFAULT '',
Apellido2 VARCHAR (30) NOT NULL DEFAULT '',
Pseudónimo VARCHAR (25) NOT NULL DEFAULT '',
PRIMARY KEY (Idautor)
);

CREATE TABLE IF NOT EXISTS Editoriales(
Cod_Editorial INT UNSIGNED AUTO_INCREMENT,
Nombre VARCHAR(30) NOT NULL,
Direccion VARCHAR(50) NOT NULL DEFAULT 'Dirección desconocida',
PRIMARY KEY (Cod_Editorial)
);


CREATE TABLE IF NOT EXISTS Libros(
ISBN VARCHAR(20) NOT NULL,
Idautor CHAR(5) NOT NULL,
Titulo VARCHAR(50) NOT NULL,
Estilo VARCHAR(50) NOT NULL,
idEditorial INT UNSIGNED NOT NULL,
Fecha_Edicion DATE NOT NULL,
PRIMARY KEY (ISBN),
FOREIGN KEY (Idautor) REFERENCES Autores(Idautor),
ON UPDATE CASCADE
ON DELETE CASCADE
FOREIGN KEY (idEditorial)REFERENCES Editoriales(Cod_Editorial),
ON UPDATE CASCADE
ON DELETE CASCADE
);

