//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace servicioweb2.sw1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioWeb1Soap", Namespace="http://tempuri.org/")]
    public partial class ServicioWeb1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalcularMediaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubtotalOperationCompleted;
        
        private System.Threading.SendOrPostCallback TotalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioWeb1() {
            this.Url = global::servicioweb2.Properties.Settings.Default.servicioweb2_sw1_ServicioWeb1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AlumnoCompletedEventHandler AlumnoCompleted;
        
        /// <remarks/>
        public event CalcularMediaCompletedEventHandler CalcularMediaCompleted;
        
        /// <remarks/>
        public event SubtotalCompletedEventHandler SubtotalCompleted;
        
        /// <remarks/>
        public event TotalCompletedEventHandler TotalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Alumno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Alumno(string nombre, string apellido1, string apellido2) {
            object[] results = this.Invoke("Alumno", new object[] {
                        nombre,
                        apellido1,
                        apellido2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AlumnoAsync(string nombre, string apellido1, string apellido2) {
            this.AlumnoAsync(nombre, apellido1, apellido2, null);
        }
        
        /// <remarks/>
        public void AlumnoAsync(string nombre, string apellido1, string apellido2, object userState) {
            if ((this.AlumnoOperationCompleted == null)) {
                this.AlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlumnoOperationCompleted);
            }
            this.InvokeAsync("Alumno", new object[] {
                        nombre,
                        apellido1,
                        apellido2}, this.AlumnoOperationCompleted, userState);
        }
        
        private void OnAlumnoOperationCompleted(object arg) {
            if ((this.AlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlumnoCompleted(this, new AlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcularMedia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float CalcularMedia(float nota1, float nota2, float nota3) {
            object[] results = this.Invoke("CalcularMedia", new object[] {
                        nota1,
                        nota2,
                        nota3});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void CalcularMediaAsync(float nota1, float nota2, float nota3) {
            this.CalcularMediaAsync(nota1, nota2, nota3, null);
        }
        
        /// <remarks/>
        public void CalcularMediaAsync(float nota1, float nota2, float nota3, object userState) {
            if ((this.CalcularMediaOperationCompleted == null)) {
                this.CalcularMediaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcularMediaOperationCompleted);
            }
            this.InvokeAsync("CalcularMedia", new object[] {
                        nota1,
                        nota2,
                        nota3}, this.CalcularMediaOperationCompleted, userState);
        }
        
        private void OnCalcularMediaOperationCompleted(object arg) {
            if ((this.CalcularMediaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcularMediaCompleted(this, new CalcularMediaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Subtotal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float Subtotal(int cantidad, float precio) {
            object[] results = this.Invoke("Subtotal", new object[] {
                        cantidad,
                        precio});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void SubtotalAsync(int cantidad, float precio) {
            this.SubtotalAsync(cantidad, precio, null);
        }
        
        /// <remarks/>
        public void SubtotalAsync(int cantidad, float precio, object userState) {
            if ((this.SubtotalOperationCompleted == null)) {
                this.SubtotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubtotalOperationCompleted);
            }
            this.InvokeAsync("Subtotal", new object[] {
                        cantidad,
                        precio}, this.SubtotalOperationCompleted, userState);
        }
        
        private void OnSubtotalOperationCompleted(object arg) {
            if ((this.SubtotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubtotalCompleted(this, new SubtotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Total", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float Total(int cantidad, float precio, int iva) {
            object[] results = this.Invoke("Total", new object[] {
                        cantidad,
                        precio,
                        iva});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void TotalAsync(int cantidad, float precio, int iva) {
            this.TotalAsync(cantidad, precio, iva, null);
        }
        
        /// <remarks/>
        public void TotalAsync(int cantidad, float precio, int iva, object userState) {
            if ((this.TotalOperationCompleted == null)) {
                this.TotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTotalOperationCompleted);
            }
            this.InvokeAsync("Total", new object[] {
                        cantidad,
                        precio,
                        iva}, this.TotalOperationCompleted, userState);
        }
        
        private void OnTotalOperationCompleted(object arg) {
            if ((this.TotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TotalCompleted(this, new TotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AlumnoCompletedEventHandler(object sender, AlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CalcularMediaCompletedEventHandler(object sender, CalcularMediaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcularMediaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcularMediaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SubtotalCompletedEventHandler(object sender, SubtotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubtotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubtotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TotalCompletedEventHandler(object sender, TotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591